services:
  - type: web
    name: timing-attack-lab
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: LAB_SECRET
        sync: false
